apiVersion: v1
kind: PersistentVolume
metadata:
  name: stellio-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/stellio/pg/data"
