apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-egm-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  mountOptions:
    - nfsvers=4.0
  nfs:
    path: /srv/nfs/egm
    server: 192.168.2.3
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
